const DATA_URL='../data/netflix_titles_cleaned.csv';let titles=[],filtered=[],visible=20;const $=s=>document.querySelector(s);const grid=$('#grid');const escapeHTML=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
async function init(){try{const r=await fetch(DATA_URL);if(!r.ok)throw Error();const text=await r.text();titles=parseCSV(text).filter(x=>x.title);buildFilters();filtered=[...titles];render();stats();}catch(e){grid.innerHTML='<p class="empty">Could not load the dataset. Open this site through a local server (for example VS Code Live Server).</p>';}}
function parseCSV(text){const rows=[];let row=[],cell='',quote=false;for(let i=0;i<text.length;i++){const c=text[i],n=text[i+1];if(c==='"'&&quote&&n==='"'){cell+='"';i++;continue}if(c==='"'){quote=!quote;continue}if(c===','&&!quote){row.push(cell);cell='';continue}if((c==='\n'||c==='\r')&&!quote){if(c==='\r'&&n==='\n')i++;row.push(cell);cell='';if(row.some(Boolean))rows.push(row);row=[];continue}cell+=c}if(cell||row.length){row.push(cell);rows.push(row)}const h=rows.shift();return rows.map(r=>Object.fromEntries(h.map((k,i)=>[k.trim(),(r[i]??'').trim()])))}
function buildFilters(){const add=(id,vals)=>{const el=$(id);[...new Set(vals.filter(Boolean))].sort((a,b)=>a.localeCompare(b)).slice(0,300).forEach(v=>{const o=document.createElement('option');o.value=v;o.textContent=v;el.appendChild(o)})};add('#genreFilter',titles.flatMap(x=>(x.listed_in||'').split(',').map(s=>s.trim())));add('#countryFilter',titles.flatMap(x=>(x.country||'').split(',').map(s=>s.trim())));add('#yearFilter',titles.map(x=>x.release_year).filter(Boolean));}
function matches(x){const q=$('#searchInput').value.toLowerCase().trim();return(!q||[x.title,x.cast,x.director,x.description].join(' ').toLowerCase().includes(q))&&(!$('#typeFilter').value||x.type===$('#typeFilter').value)&&(!$('#genreFilter').value||(x.listed_in||'').includes($('#genreFilter').value))&&(!$('#yearFilter').value||String(x.release_year)===$('#yearFilter').value)&&(!$('#countryFilter').value||(x.country||'').includes($('#countryFilter').value))}
function render(){filtered=titles.filter(matches);const data=filtered.slice(0,visible);grid.innerHTML=data.length?data.map(card).join(''):'<p class="empty">No titles match your filters.</p>';$('#resultCount').textContent=`${filtered.length.toLocaleString()} titles`;$('#loadMore').style.display=visible<filtered.length?'block':'none';}
function card(x){const id=encodeURIComponent(x.show_id);return `<article class="card" data-id="${id}"><button class="save" data-save="${id}" title="Add to My List">+</button><div class="poster">${escapeHTML(x.title)}<br><small>${escapeHTML(x.type||'')}</small></div><div class="card-body"><h3>${escapeHTML(x.title)}</h3><div class="meta">${escapeHTML(x.release_year||'')} · ${escapeHTML(x.rating||'NR')} · ${escapeHTML(x.duration||'')}</div></div></article>`}
function openDetails(id){const x=titles.find(t=>String(t.show_id)===decodeURIComponent(id));if(!x)return;const saved=getSaved();$('#detailContent').innerHTML=`<p class="eyebrow">${escapeHTML(x.type||'TITLE')}</p><h2 class="detail-title">${escapeHTML(x.title)}</h2><p class="detail-meta">${escapeHTML(x.release_year||'')} · ${escapeHTML(x.rating||'Not rated')} · ${escapeHTML(x.duration||'')} · ${escapeHTML(x.country||'')}</p><p class="detail-copy">${escapeHTML(x.description||'No description available.')}</p><h4>Genres</h4><div class="chips">${(x.listed_in||'').split(',').filter(Boolean).map(g=>`<span class="chip">${escapeHTML(g.trim())}</span>`).join('')}</div><h4>Cast</h4><p class="detail-copy">${escapeHTML(x.cast||'Not listed')}</p><h4>Director</h4><p class="detail-copy">${escapeHTML(x.director||'Not listed')}</p><button class="primary" data-modal-save="${encodeURIComponent(x.show_id)}">${saved.has(String(x.show_id))?'✓ In My List':'+ Add to My List'}</button>`;$('#modal').classList.remove('hidden')}
function getSaved(){return new Set(JSON.parse(localStorage.getItem('streamflix-list')||'[]'))}function toggleSave(id){const s=getSaved(),key=decodeURIComponent(id);s.has(key)?s.delete(key):s.add(key);localStorage.setItem('streamflix-list',JSON.stringify([...s]));renderMyList();toast(s.has(key)?'Added to My List':'Removed from My List')}
function renderMyList(){const s=getSaved(),items=titles.filter(x=>s.has(String(x.show_id)));$('#myListGrid').innerHTML=items.map(card).join('');$('#emptyList').style.display=items.length?'none':'block'}function stats(){$('#totalStat').textContent=titles.length.toLocaleString();$('#movieStat').textContent=titles.filter(x=>x.type==='Movie').length.toLocaleString();$('#showStat').textContent=titles.filter(x=>x.type==='TV Show').length.toLocaleString();$('#yearStat').textContent=Math.max(...titles.map(x=>+x.release_year||0));drawChart()}
function drawChart(){const c=$('#yearChart'),ctx=c.getContext('2d'),w=c.width=c.clientWidth*2,h=c.height=c.clientHeight*2;ctx.scale(2,2);const years={};titles.forEach(x=>{if(x.release_year)years[x.release_year]=(years[x.release_year]||0)+1});const vals=Object.entries(years).sort((a,b)=>a[0]-b[0]).slice(-20),max=Math.max(...vals.map(x=>x[1]));ctx.strokeStyle='#e50914';ctx.lineWidth=3;ctx.beginPath();vals.forEach(([y,v],i)=>{const px=i*(c.clientWidth/(vals.length-1)),py=c.clientHeight-20-(v/max)*(c.clientHeight-45);i?ctx.lineTo(px,py):ctx.moveTo(px,py)});ctx.stroke();ctx.fillStyle='#888';ctx.font='10px Arial';vals.forEach(([y],i)=>ctx.fillText(y,i*(c.clientWidth/(vals.length-1))-12,c.clientHeight-4))}
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1800)}
$('#searchInput').addEventListener('input',()=>{visible=20;render()});['typeFilter','genreFilter','yearFilter','countryFilter'].forEach(id=>$('#'+id).addEventListener('change',()=>{visible=20;render()}));$('#clearFilters').onclick=()=>{$('#searchInput').value='';['typeFilter','genreFilter','yearFilter','countryFilter'].forEach(id=>$('#'+id).value='');visible=20;render()};$('#loadMore').onclick=()=>{visible+=20;render()};document.addEventListener('click',e=>{const cardEl=e.target.closest('.card');if(e.target.dataset.save)toggleSave(e.target.dataset.save);else if(e.target.dataset.modalSave){toggleSave(e.target.dataset.modalSave);openDetails(e.target.dataset.modalSave)}else if(cardEl)openDetails(cardEl.dataset.id);if(e.target.matches('[data-close]'))$('#modal').classList.add('hidden')});$('#randomBtn').onclick=()=>{if(!titles.length)return;openDetails(encodeURIComponent(titles[Math.floor(Math.random()*titles.length)].show_id))};$('#searchBtn').onclick=()=>$('#searchInput').focus();renderMyList();init();
